spring.datasource.url=ep-empty-brook-a4h0pqx6-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_f2EMrpiz1DIg

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
